name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --allow-all --coverage=cov/

      - name: Export coverage file
        run: deno coverage --lcov cov/ > cov.lcov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
